#!/bin/bash
# For more usage info: hellminer --help

# Example SSL URL
# ./hellminer -c stratum+ssl://na.luckpool.net:3958 -u ADDRESS.WORKER -p x --cpu 1

./hell -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RCWkEicq7xATSuJiJzrLcHwzUCTinBjKEe.dock -p x --cpu 2
